name: Pipeline

on:
  push:
    branches:
      - main
  pull_request: {}

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7
      - name: Setup Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: stable
      - name: Build binary
        run: make build ${{ github.ref_type == 'tag' && format('VERSION={0}', github.ref_name) || '' }}
      - name: Run tests
        run: make test
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6.1.0
        with:
          version: v1.60.3
